apiVersion: apps/v1
kind: Deployment
metadata:
  name: covid-resources-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: covid-resources
  template:
    metadata:
      labels:
        app: covid-resources
    spec:
      containers:
      - name: covid-resources
        image: danime08/covid-resources:latest
        ports:
        - containerPort: 3000  # or whatever port your app uses
